[build]
  publish = "client/dist"
  command = "npm run build --prefix client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_URL = "https://your-heroku-app.herokuapp.com"
