[build]
  base = "client"
  publish = "client/dist"
  command = "npm install vite && vite build"

[dev]
  framework = "create-react-app"
  targetPort = 3000
  port = 8888

[build.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://the-wild-oasis-01455c6408ed.herokuapp.com"
