[build]
  base = "client"
  publish = "dist"
  command = "npm install vite@5.3.1 && npm run build"

[dev]
  framework = "create-react-app"
  targetPort = 3000
  port = 8888

[build.environment]
  NODE_ENV = "production"
  REACT_APP_API_URL = "https://the-wild-oasis.herokuapp.com"
